In [2]:
import pandas as pd
def normalize_to_month_start(df, date_col):
    # Chuyển về datetime nếu chưa phải
    df[date_col] = pd.to_datetime(df[date_col])
    # Quy chuẩn: Tháng 12/2024 (bất kể ngày 01 hay 31) -> 2024-12-01
    df[date_col] = df[date_col].dt.to_period('M').dt.to_timestamp()
    return df

In [5]:
df_argentina = pd.read_csv(r'data\processed\All_weather_data\argentina_weather.csv')
electric_data = pd.read_csv(r'data\raw\ember_data\all_country_data_cleaned.csv')

df_argentina = normalize_to_month_start(df_argentina, 'date')
df_argentina.head()

┌──────────────────────────────── ⚠️ Warning ─────────────────────────────────┐
│ UserWarning in                                                              │
│ C:\Users\Admin\AppData\Local\Temp\ipykernel_14480\1584404046.py:4           │
│ Parsing dates in %d/%m/%Y format when dayfirst=False (the default) was      │
│ specified. Pass `dayfirst=True` or specify a format to silence this         │
│ warning.                                                                    │
└─────────────────────────────────────────────────────────────────────────────┘

        date  precipitation      solar  humidity  temperature       area
0 2019-01-01       12163.76  24.589283  9.633673    17.910753  Argentina
1 2019-02-01        7933.66  22.317804  9.121690    17.687442  Argentina
2 2019-03-01       11186.12  17.091097  8.816683    15.859587  Argentina
3 2019-04-01        9478.46  12.523373  8.139262    14.111348  Argentina
4 2019-05-01        8804.88   8.608428  7.180509    11.298165  Argentina

In [11]:
# combine dữ liệu dựa vào cột entity = arena và date
combined_df = pd.concat([electric_data, df_argentina], keys=['electric', 'weather'], axis=1)
combined_df.head()

    electric                                                      weather  \
      entity entity code        date     series generation_TWh       date
0  Argentina         ARG  01/01/2018  Bioenergy           0.02 2019-01-01
1  Argentina         ARG  01/01/2018       Coal           0.26 2019-02-01
2  Argentina         ARG  01/01/2018        Gas           7.79 2019-03-01
3  Argentina         ARG  01/01/2018      Hydro           3.69 2019-04-01
4  Argentina         ARG  01/01/2018    Nuclear           0.64 2019-05-01


  precipitation      solar  humidity temperature       area
0      12163.76  24.589283  9.633673   17.910753  Argentina
1       7933.66  22.317804  9.121690   17.687442  Argentina
2      11186.12  17.091097  8.816683   15.859587  Argentina
3       9478.46  12.523373  8.139262   14.111348  Argentina
4       8804.88   8.608428  7.180509   11.298165  Argentina