In [66]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [67]:
def normalize_to_month_start(df, date_col):
    # Chuyển về datetime nếu chưa phải
    df[date_col] = pd.to_datetime(df[date_col])
    # Quy chuẩn: Tháng 12/2024 (bất kể ngày 01 hay 31) -> 2024-12-01
    df[date_col] = df[date_col].dt.to_period('M').dt.to_timestamp()
    return df

In [68]:
humidity_data = pd.read_csv(r"data\raw\weather_data\humidity_vietnam_tft.csv")
preciptiation_data = pd.read_csv(r"data\raw\weather_data\precipitation_vietnam_tft.csv")
solar_data = pd.read_csv(r"data\raw\weather_data\solar_radiation_vietnam_tft.csv")
temp_data = pd.read_csv(r"data\raw\weather_data\temp_vietnam_tft.csv")
humidity_data

          date  humidity_HN  humidity_DN  humidity_HCM
0   2019-01-31    82.064516    87.129032     66.709677
1   2019-02-28    84.357143    87.785714     62.428571
2   2019-03-31    84.419355    85.000000     65.806452
3   2019-04-30    85.433333    81.366667     67.666667
4   2019-05-31    83.322581    76.612903     81.419355
..         ...          ...          ...           ...
77  2025-06-30    83.466667    75.566667     86.533333
78  2025-07-31    84.677419    73.709677     84.774194
79  2025-08-31    85.419355    73.903226     85.838710
80  2025-09-30    84.033333    84.366667     88.100000
81  2025-10-31    81.161290    86.580645     86.516129

[82 rows x 4 columns]

In [69]:
cols_to_mean = ['humidity_HN', 'humidity_DN', 'humidity_HCM']
humidity_data['humidity_mean'] = humidity_data[cols_to_mean].mean(axis=1)
humidity_data.drop(columns=cols_to_mean, inplace=True)
humidity_data = normalize_to_month_start(humidity_data, 'date')
humidity_data

         date  humidity_mean
0  2019-01-01      78.634409
1  2019-02-01      78.190476
2  2019-03-01      78.408602
3  2019-04-01      78.155556
4  2019-05-01      80.451613
..        ...            ...
77 2025-06-01      81.855556
78 2025-07-01      81.053763
79 2025-08-01      81.720430
80 2025-09-01      85.500000
81 2025-10-01      84.752688

[82 rows x 2 columns]

In [70]:
cols_to_mean = ['precip_HN', 'precip_DN', 'precip_HCM']
preciptiation_data['precip_mean'] = preciptiation_data[cols_to_mean].mean(axis=1)
preciptiation_data.drop(columns=cols_to_mean, inplace=True)
preciptiation_data = normalize_to_month_start(preciptiation_data, 'date')
preciptiation_data

         date  precip_mean
0  2019-01-01   107.366667
1  2019-02-01    30.700000
2  2019-03-01    33.866667
3  2019-04-01   109.033333
4  2019-05-01   194.633333
..        ...          ...
77 2025-06-01   406.166667
78 2025-07-01   264.766667
79 2025-08-01   358.233333
80 2025-09-01   378.866667
81 2025-10-01   464.066667

[82 rows x 2 columns]

In [71]:
cols_to_mean = ['solar_HN', 'solar_DN', 'solar_HCM']
solar_data['solar_mean'] = solar_data[cols_to_mean].mean(axis=1)
solar_data.drop(columns=cols_to_mean, inplace=True)
solar_data = normalize_to_month_start(solar_data, 'date')
solar_data

         date  solar_mean
0  2019-01-01  401.016667
1  2019-02-01  466.336667
2  2019-03-01  522.160000
3  2019-04-01  570.526667
4  2019-05-01  585.696667
..        ...         ...
77 2025-06-01  577.640000
78 2025-07-01  593.096667
79 2025-08-01  579.103333
80 2025-09-01  522.990000
81 2025-10-01  472.343333

[82 rows x 2 columns]

In [72]:
cols_to_mean = ['HN_temp', 'DN_temp', 'HCM_temp']

temp_data['temp_mean'] = temp_data[cols_to_mean].mean(axis=1)
col_drop = [col for col in temp_data.columns if col not in ['date', 'temp_mean']]
temp_data.drop(columns=col_drop, inplace=True)
temp_data = normalize_to_month_start(temp_data, 'date')
temp_data

         date  temp_mean
0  2019-01-01  22.087097
1  2019-02-01  24.680952
2  2019-03-01  25.594624
3  2019-04-01  28.315556
4  2019-05-01  28.589247
..        ...        ...
77 2025-06-01  28.485556
78 2025-07-01  28.627957
79 2025-08-01  28.211828
80 2025-09-01  27.268889
81 2025-10-01  26.095699

[82 rows x 2 columns]

In [73]:
combie_data = humidity_data.merge(preciptiation_data, on='date', how='inner')
combie_data = combie_data.merge(solar_data, on='date', how='inner')
combie_data = combie_data.merge(temp_data, on='date', how='inner')
#combie_data = combie_data.merge(humidity_data, on='date', how='inner')
combie_data.isnull().sum()

date             0
humidity_mean    0
precip_mean      0
solar_mean       0
temp_mean        0
dtype: int64

In [75]:
combie_data.to_csv(r"data\processed\weather_vietnam_monthly.csv", index=False)

In [76]:
combie_data

         date  humidity_mean  precip_mean  solar_mean  temp_mean
0  2019-01-01      78.634409   107.366667  401.016667  22.087097
1  2019-02-01      78.190476    30.700000  466.336667  24.680952
2  2019-03-01      78.408602    33.866667  522.160000  25.594624
3  2019-04-01      78.155556   109.033333  570.526667  28.315556
4  2019-05-01      80.451613   194.633333  585.696667  28.589247
..        ...            ...          ...         ...        ...
77 2025-06-01      81.855556   406.166667  577.640000  28.485556
78 2025-07-01      81.053763   264.766667  593.096667  28.627957
79 2025-08-01      81.720430   358.233333  579.103333  28.211828
80 2025-09-01      85.500000   378.866667  522.990000  27.268889
81 2025-10-01      84.752688   464.066667  472.343333  26.095699

[82 rows x 5 columns]