In [22]:
import pandas as pd
def normalize_to_month_start(df, date_col):
    # Chuyển về datetime nếu chưa phải (thêm dayfirst=True để parse đúng ngày/tháng)
    df[date_col] = pd.to_datetime(df[date_col], dayfirst=True)

    # Quy chuẩn: Tháng 12/2024 (bất kể ngày 01 hay 31) -> 2024-12-01
    df[date_col] = df[date_col].dt.to_period('M').dt.to_timestamp()

    # drop hết dữ liệu trước tháng 1/2018
    df = df[df[date_col] >= '2018-01-01']

    return df

In [23]:
# df_argentina = pd.read_csv(r'data\processed\All_weather_data\argentina_weather.csv')
electric_data = pd.read_csv(r'C:\Users\ADMIN\Downloads\MODEL_TFT\data\raw\ember_data\all_country_data.csv')
electric_data.head(30)

,entity,entity code,date,series,generation_TWh
0,Australia,AUS,01/01/2018,Demand,19.96
1,Australia,AUS,01/01/2018,Clean,3.27
2,Australia,AUS,01/01/2018,Fossil,16.69
3,Australia,AUS,01/01/2018,Gas and Other Fossil,2.53
4,Australia,AUS,01/01/2018,"Hydro, Bioenergy and Other Renewables",1.12
5,Australia,AUS,01/01/2018,Renewables,3.27
6,Australia,AUS,01/01/2018,Wind and Solar,2.15
7,Australia,AUS,01/01/2018,Bioenergy,0.03
8,Australia,AUS,01/01/2018,Coal,14.16
9,Australia,AUS,01/01/2018,Gas,2.53
10,Australia,AUS,01/01/2018,Hydro,1.09
11,Australia,AUS,01/01/2018,Other Fossil,0.00
12,Australia,AUS,01/01/2018,Solar,1.00
13,Australia,AUS,01/01/2018,Wind,1.15
14,Australia,AUS,01/01/2018,Total Generation,19.96
15,Australia,AUS,01/01/2018,Net Imports,0.00
16,Australia,AUS,01/02/2018,Demand,17.73
17,Australia,AUS,01/02/2018,Clean,2.91
18,Australia,AUS,01/02/2018,Fossil,14.82
19,Australia,AUS,01/02/2018,Gas and Other Fossil,2.11
20,Australia,AUS,01/02/2018,"Hydro, Bioenergy and Other Renewables",0.97
21,Australia,AUS,01/02/2018,Renewables,2.91
22,Australia,AUS,01/02/2018,Wind and Solar,1.94
23,Australia,AUS,01/02/2018,Bioenergy,0.03
24,Australia,AUS,01/02/2018,Coal,12.71
25,Australia,AUS,01/02/2018,Gas,2.10
26,Australia,AUS,01/02/2018,Hydro,0.94
27,Australia,AUS,01/02/2018,Other Fossil,0.01
28,Australia,AUS,01/02/2018,Solar,0.84
29,Australia,AUS,01/02/2018,Wind,1.10

In [24]:

# df_argentina = normalize_to_month_start(df_argentina, 'date')
electric_data = normalize_to_month_start(electric_data, 'date')
electric_data.head()

,entity,entity code,date,series,generation_TWh
0,Australia,AUS,2018-01-01,Demand,19.96
1,Australia,AUS,2018-01-01,Clean,3.27
2,Australia,AUS,2018-01-01,Fossil,16.69
3,Australia,AUS,2018-01-01,Gas and Other Fossil,2.53
4,Australia,AUS,2018-01-01,"Hydro, Bioenergy and Other Renewables",1.12

In [25]:
electric_data.head(30)

,entity,entity code,date,series,generation_TWh
0,Australia,AUS,2018-01-01,Demand,19.96
1,Australia,AUS,2018-01-01,Clean,3.27
2,Australia,AUS,2018-01-01,Fossil,16.69
3,Australia,AUS,2018-01-01,Gas and Other Fossil,2.53
4,Australia,AUS,2018-01-01,"Hydro, Bioenergy and Other Renewables",1.12
5,Australia,AUS,2018-01-01,Renewables,3.27
6,Australia,AUS,2018-01-01,Wind and Solar,2.15
7,Australia,AUS,2018-01-01,Bioenergy,0.03
8,Australia,AUS,2018-01-01,Coal,14.16
9,Australia,AUS,2018-01-01,Gas,2.53
10,Australia,AUS,2018-01-01,Hydro,1.09
11,Australia,AUS,2018-01-01,Other Fossil,0.00
12,Australia,AUS,2018-01-01,Solar,1.00
13,Australia,AUS,2018-01-01,Wind,1.15
14,Australia,AUS,2018-01-01,Total Generation,19.96
15,Australia,AUS,2018-01-01,Net Imports,0.00
16,Australia,AUS,2018-02-01,Demand,17.73
17,Australia,AUS,2018-02-01,Clean,2.91
18,Australia,AUS,2018-02-01,Fossil,14.82
19,Australia,AUS,2018-02-01,Gas and Other Fossil,2.11
20,Australia,AUS,2018-02-01,"Hydro, Bioenergy and Other Renewables",0.97
21,Australia,AUS,2018-02-01,Renewables,2.91
22,Australia,AUS,2018-02-01,Wind and Solar,1.94
23,Australia,AUS,2018-02-01,Bioenergy,0.03
24,Australia,AUS,2018-02-01,Coal,12.71
25,Australia,AUS,2018-02-01,Gas,2.10
26,Australia,AUS,2018-02-01,Hydro,0.94
27,Australia,AUS,2018-02-01,Other Fossil,0.01
28,Australia,AUS,2018-02-01,Solar,0.84
29,Australia,AUS,2018-02-01,Wind,1.10

In [26]:
electric_data.to_csv(r'C:\Users\ADMIN\Downloads\MODEL_TFT\data\raw\ember_data\all_country_data.csv', index=False)