In [12]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [14]:
df = pd.read_csv(r'C:\Users\ADMIN\Downloads\MODEL_TFT\data\raw\ember_data\all_country_data2.csv')

In [15]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12227 entries, 0 to 12226
Data columns (total 18 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Area                 12227 non-null  object
 1   ISO 3 code           12227 non-null  object
 2   Date                 12227 non-null  object
 3   Area type            12227 non-null  object
 4   Continent            12227 non-null  object
 5   Ember region         12227 non-null  object
 6   EU                   12227 non-null  int64
 7   OECD                 12227 non-null  int64
 8   G20                  12227 non-null  int64
 9   G7                   12227 non-null  int64
 10  ASEAN                12227 non-null  int64
 11  Category             12227 non-null  object
 12  Subcategory          12227 non-null  object
 13  Variable             12227 non-null  object
 14  Unit                 12227 non-null  object
 15  Value                12227 non-null  float64
 16  YoY absolute change  10799 non-null  float64
 17  YoY % change         10116 non-null  float64
dtypes: float64(3), int64(5), object(10)
memory usage: 1.7+ MB

0,1,2,13,15

In [16]:
# filter data
data = df.drop(columns=[ 'Area type', 'Continent', 'Ember region', 'EU', 'OECD', 'G20', 'G7', 'ASEAN','Category', 'Subcategory', 'Unit','YoY absolute change', 'YoY % change'])
data.head()

        Area ISO 3 code        Date   Variable  Value
0  Argentina        ARG  01/01/2018  Bioenergy   0.02
1  Argentina        ARG  01/01/2018       Coal   0.26
2  Argentina        ARG  01/01/2018        Gas   7.79
3  Argentina        ARG  01/01/2018      Hydro   3.69
4  Argentina        ARG  01/01/2018    Nuclear   0.64

In [19]:
# Đổi tên lần lượt các cột thành : entity, entity_code, date, series, generation_twh
data.columns = ['entity', 'entity code', 'date', 'series', 'generation_TWh']
data.head()

      entity entity code        date     series  generation_TWh
0  Argentina         ARG  01/01/2018  Bioenergy            0.02
1  Argentina         ARG  01/01/2018       Coal            0.26
2  Argentina         ARG  01/01/2018        Gas            7.79
3  Argentina         ARG  01/01/2018      Hydro            3.69
4  Argentina         ARG  01/01/2018    Nuclear            0.64

In [21]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12227 entries, 0 to 12226
Data columns (total 5 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   entity          12227 non-null  object
 1   entity code     12227 non-null  object
 2   date            12227 non-null  object
 3   series          12227 non-null  object
 4   generation_TWh  12227 non-null  float64
dtypes: float64(1), object(4)
memory usage: 477.7+ KB

In [22]:
data.to_csv(r'C:\Users\ADMIN\Downloads\MODEL_TFT\data\raw\ember_data\all_country_data_cleaned.csv', index=False)