In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv(r'C:\Users\ADMIN\Downloads\MODEL_TFT\data\raw\ember_data\all_20_country_twh.csv')

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 31640 entries, 0 to 31639
Data columns (total 18 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Area                 31640 non-null  object
 1   ISO 3 code           31640 non-null  object
 2   Date                 31640 non-null  object
 3   Area type            31640 non-null  object
 4   Continent            31640 non-null  object
 5   Ember region         31640 non-null  object
 6   EU                   31640 non-null  int64
 7   OECD                 31640 non-null  int64
 8   G20                  31640 non-null  int64
 9   G7                   31640 non-null  int64
 10  ASEAN                31640 non-null  int64
 11  Category             31640 non-null  object
 12  Subcategory          31640 non-null  object
 13  Variable             31640 non-null  object
 14  Unit                 31640 non-null  object
 15  Value                31640 non-null  float64
 16  YoY absolute change  30395 non-null  float64
 17  YoY % change         27890 non-null  float64
dtypes: float64(3), int64(5), object(10)
memory usage: 4.3+ MB

0,1,2,13,15

In [4]:
# filter data
data = df.drop(columns=[ 'Area type', 'Continent', 'Ember region', 'EU', 'OECD', 'G20', 'G7', 'ASEAN','Category', 'Subcategory', 'Unit','YoY absolute change', 'YoY % change'])
data.head()

,Area,ISO 3 code,Date,Variable,Value
0,Australia,AUS,01/01/2018,Demand,19.96
1,Australia,AUS,01/01/2018,Clean,3.27
2,Australia,AUS,01/01/2018,Fossil,16.69
3,Australia,AUS,01/01/2018,Gas and Other Fossil,2.53
4,Australia,AUS,01/01/2018,"Hydro, Bioenergy and Other Renewables",1.12

In [5]:
# Đổi tên lần lượt các cột thành : entity, entity_code, date, series, generation_twh
data.columns = ['entity', 'entity code', 'date', 'series', 'generation_TWh']
data.head()

,entity,entity code,date,series,generation_TWh
0,Australia,AUS,01/01/2018,Demand,19.96
1,Australia,AUS,01/01/2018,Clean,3.27
2,Australia,AUS,01/01/2018,Fossil,16.69
3,Australia,AUS,01/01/2018,Gas and Other Fossil,2.53
4,Australia,AUS,01/01/2018,"Hydro, Bioenergy and Other Renewables",1.12

In [6]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 31640 entries, 0 to 31639
Data columns (total 5 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   entity          31640 non-null  object
 1   entity code     31640 non-null  object
 2   date            31640 non-null  object
 3   series          31640 non-null  object
 4   generation_TWh  31640 non-null  float64
dtypes: float64(1), object(4)
memory usage: 1.2+ MB

In [7]:
data.to_csv(r'C:\Users\ADMIN\Downloads\MODEL_TFT\data\raw\ember_data\all_country_data.csv', index=False)